#define TAG_MSJ_PLANO "MPL"
#define TAG_VIEW_OBJETO_SIMPLE "VOS"
#define TAG_VIEW_OBJETO_CON_ANCHO "VOCA"
#define TAG_VIEW_OBJETO_UNION "VOU"
#define OBJ_SIMPLE_S_BALANCIN 'b'
#define OBJ_SIMPLE_S_PELOTAJUEGO 'p'
#define OBJ_SIMPLE_S_BOLABOLICHE 'h'
#define OBJ_SIMPLE_S_GLOBO 'g'
#define OBJ_CON_ANCHO_S_PLATAFORMA 't'
#define OBJ_CON_ANCHO_S_CINTA 'c'
#define OBJ_UNION_S_SOGA_ESTATICA 's'
#define OBJ_UNION_S_CORREA_ESTATICA 'e'
#define OBJ_UNION_S_SOGA 'x'
#define OBJ_UNION_S_CORREA 'y'
#define OBJ_CON_ANCHO_S_ENGRANAJE 'j'
#define OBJ_SIMPLE_S_MOTOR 'm'

#define TAG_CLICK "EC"

#define TAG_FACTORY_BALANCIN "FB"
#define TAG_FACTORY_MOTOR "FM"
#define TAG_FACTORY_ENGRANAJE "FE"
#define TAG_FACTORY_SOGA "FS"
#define TAG_FACTORY_CORREA "FC"
#define TAG_FACTORY_CINTA "FA"
#define TAG_FACTORY_PLATAFORMA "FP"
#define TAG_FACTORY_BOLA "FL"
#define TAG_FACTORY_GLOBO "FG"





#define MSJ_JUGADOR_ACEPTADO "MJA"
#define MSJ_JUGADOR_RECHAZADO "MJR"
#define TIMEOUT 90

