#define TAG_MSJ_PLANO "MPL"
#define TAG_VIEW_OBJETO_SIMPLE "VOS"
#define TAG_VIEW_OBJETO_CON_ANCHO "VOCA"
#define TAG_VIEW_OBJETO_UNION "VOU"

#define TAG_CLICK "EC"

#define TAG_FACTORY_BALANCIN "FB"
#define TAG_FACTORY_MOTOR "FM"
#define TAG_FACTORY_ENGRANAJE "FE"
#define TAG_FACTORY_SOGA "FS"
#define TAG_FACTORY_CORREA "FC"
#define TAG_FACTORY_CINTA "FA"
#define TAG_FACTORY_PLATAFORMA "FP"
#define TAG_FACTORY_BOLA "FL"
#define TAG_FACTORY_GLOBO "FG"





#define MSJ_JUGADOR_ACEPTADO "MJA"
#define MSJ_JUGADOR_RECHAZADO "MJR"
#define TIMEOUT 90

