#define TAG_MSJ_PLANO "MPL"
#define TAG_VIEW_SOGA "VSO"
#define TAG_VIEW_CORREA "VCO"
#define TAG_VIEW_OBJETO_SIMPLE "VOS"
#define TAG_VIEW_OBJETO_CON_ANCHO "VOCA"
#define MSJ_JUGADOR_ACEPTADO "MJA"
#define MSJ_JUGADOR_RECHAZADO "MJR"
#define TIMEOUT 90
