#define TAG_MSJ_PLANO "MPL"
#define TAG_VIEW_OBJETO_SIMPLE "VOS"
#define TAG_VIEW_OBJETO_CON_ANCHO "VOCA"
#define TAG_VIEW_OBJETO_UNION "VOU"
#define TAG_INTERNO_DRAW "ID"
#define TAG_INTERNO_CONEXION "IC"
#define OBJ_SIMPLE_S_BALANCIN 'b'
#define OBJ_SIMPLE_S_PELOTAJUEGO 'p'
#define OBJ_SIMPLE_S_BOLABOLICHE 'h'
#define OBJ_SIMPLE_S_GANCHO 'a'
#define OBJ_SIMPLE_S_GLOBO 'g'
#define OBJ_CON_ANCHO_S_PLATAFORMA 't'
#define OBJ_CON_ANCHO_S_CINTA 'c'
#define OBJ_UNION_S_CORREA_ESTATICA 'e'
#define OBJ_UNION_S_SOGA 'x'
#define OBJ_UNION_S_SOGA_ESTATICA 'i'
#define OBJ_UNION_S_CORREA 'y'
#define OBJ_CON_ANCHO_S_ENGRANAJE 'j'
#define OBJ_SIMPLE_S_MOTOR 'm'
#define OBJ_SIMPLE_S_YUNQUE 'y'

#define TAG_JUGADOR_LISTO "JL"
#define TAG_MSJ_NOTIMEOUT "NTO"
#define TAG_MOUSE_MOTION "EM"
#define TAG_CLICK "EC"
#define TAG_DIBUJADO "ED"
#define TAG_CREACION_OBJETO "CO"
#define TAG_FIN_DIBUJADO "FD"

#define TAG_FACTORY_BALANCIN "FB"
#define TAG_FACTORY_BOLA "FL"
#define TAG_FACTORY_CINTA "FA"
#define TAG_FACTORY_CORREA "FC"
#define TAG_FACTORY_ENGRANAJE "FE"
#define TAG_FACTORY_GLOBO "FG"
#define TAG_FACTORY_MOTOR "FM"
#define TAG_FACTORY_PELOTA "FO"
#define TAG_FACTORY_SOGA "FS"
#define TAG_FACTORY_PLATAFORMA "FP"
#define TAG_FACTORY_YUNQUE "FY"
#define TAG_FACTORY_GANCHO "FF"




#define MSJ_JUGADOR_ACEPTADO "MJA"
#define MSJ_JUGADOR_RECHAZADO "MJR"
#define MSJ_CONFIG_JUGADOR "MJC"
#define TIMEOUT 90

