/*
 * Constantes.h
 *
 *  Created on: 09/10/2013
 *      Author: jonathan
 */

#ifndef CONSTANTES_H_
#define CONSTANTES_H_

// NUMERO DE JUGADOR POR DEFECTO. PARA HACER REFERENCIA A LAS FIGURAS DEL NIVEL
#define NUMERO_JUGADOR_DEFECTO -1
/*
 * PARAMETRIZACION B2D
 */
#define TIEMPO_ITERACION 1/60.0 //SEGUNDOS
#define ITERACIONES_VELOCIDAD 10.0
#define ITERACIONES_POSICION 8.0

/*
 * FACTORY FIGURAS
 */
#define RADIO_GANCHO 1.0
#define RADIO_PELOTA 3.0
#define RADIO_BOLA 3.0
#define RADIO_POLEA 4.0
#define RADIO_GLOBO 3.5
#define ANCHO_PLATAFORMA 10.0
#define ALTO_PLATAFORMA 2.5
#define ANCHO_YUNQUE 6.0
#define ALTO_YUNQUE 6.0
#define ANCHO_CLAVO 6.0
#define ALTO_CLAVO 3.0


#define ANCHO_BALANCIN 15.0
#define ALTO_BALANCIN 1.6
#define ANCHO_CARRITO 20.0
#define ALTO_CARRITO 10.0
#define RADIO_RUEDA_CARRITO 1.7

#define ALTO_CINTA 5
#define ANCHO_CINTA 20
#define RADIO_EJE_CINTA 3.0

#define CATEGORIA_FIGURAS 0X0002
#define CATEGORIA_RANGO_ENGRANAJE 0X0004
#define CATEGORIA_UNION 0X0008
#define CATEGORIA_CENTRO_CINTA 0X0010
#define CATEGORIA_PUNTA_CLAVO 0X0012
#define MASCARA_PICKUP 6 //figuras y uniones
#define RADIO_ENGRANAJE_CHICO 2.5
#define RADIO_ENGRANAJE 3.5
#define RADIO_ENGRANAJE_GRANDE 5.5
#define RADIO_MOTOR 3.5
//#define
//#define
//#define
//#define
//#define
//#define
//#define
//#define
//#define
//#define


#endif /* CONSTANTES_H_ */
